<a href="https://colab.research.google.com/github/samadhiy/Machine-Learning/blob/main/Lab_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab Sheet 2 - Logistic Regression

22UG2-0013

Step 1: Import Required Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Step 2: Upload & Load the Dataset (Colab)

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving Social_Network_Ads.csv to Social_Network_Ads (1).csv


In [ ]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset.head()


,Age,EstimatedSalary,Purchased
0,56,23392,0
1,46,45535,0
2,32,128569,1
3,25,67256,0
4,38,104135,1


Step 3: Dataset Information

In [ ]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              100 non-null    int64
 1   EstimatedSalary  100 non-null    int64
 2   Purchased        100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB


Step 4: Select Features and Target

In [ ]:
X = dataset[['Age', 'EstimatedSalary']]
y = dataset['Purchased']


Step 5: Split Dataset into Training & Testing Sets

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)


Step 6: Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


Step 7: Train Logistic Regression Model

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)


LogisticRegression(random_state=0)

Step 8: Predict Test Results

In [ ]:
y_pred = classifier.predict(X_test)


Step 9: Accuracy Score

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy


0.84

Step 10: Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm


array([[ 9,  4],
       [ 0, 12]])

Step 11: Predict Purchase for a New User

In [ ]:
new_user = sc.transform([[30, 50000]])  # Age = 30, Salary = 50000
prediction = classifier.predict(new_user)
prediction


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])

Step 12: Probability of Purchase

In [ ]:
probability = classifier.predict_proba(new_user)
probability


array([[0.70577698, 0.29422302]])